name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install nanobind
      run: |
        pip3 install nanobind

    - name: Create build directory
      run: |
        mkdir build
        cd build

    - name: Run CMake
      run: |
        cd build
        cmake ..

    - name: Build with Make
      run: |
        cd build
        make
